### PR TITLE
Add Mat3 to Rotor3 conversion

### PR DESCRIPTION
**Pull request by thenlevy**
Here is a proposition to implement issue #61 
I made a separated `impl` block because I am not familiar with the strctures represented by `Mat3x4` or `Mat3x8`

Here is a code that can be used to test the correctness of the implementation
```
use rand::prelude::*;
use ultraviolet::*;
use std::f32::consts::FRAC_PI_2;
use std::f32::consts::PI;
fn main() {
    for i in 0..=10 {
        let alpha = (rand::random::<f32>() - 0.5) * std::f32::consts::PI;
        let beta = (rand::random::<f32>() - 0.5) * std::f32::consts::PI;
        let gamma = (rand::random::<f32>() - 0.5) * std::f32::consts::PI;
        let rotor = Rotor3::from_euler_angles(alpha, beta, gamma);
        let mat = rotor.into_matrix();
        let rotor2 = mat.into_rotor3();
        println!("test {}", i);
        println!("{:?}", rotor);
        println!("{:?}", rotor2);
        println!("========================");
    }

    // corner cases
    for i in 0..=10 {
        let alpha = {
            let x = rand::random::<u8>();
            match x % 4 {
                0 => -FRAC_PI_2,
                1 => 0.,
                2 => FRAC_PI_2,
                3 => PI,
                _ => unreachable!()
            }
        };
        let beta = {
            let x = rand::random::<u8>();
            match x % 4 {
                0 => -FRAC_PI_2,
                1 => 0.,
                2 => FRAC_PI_2,
                3 => PI,
                _ => unreachable!()
            }
        };
        let gamma = {
            let x = rand::random::<u8>();
            match x % 4 {
                0 => -FRAC_PI_2,
                1 => 0.,
                2 => FRAC_PI_2,
                3 => PI,
                _ => unreachable!()
            }
        };
        let rotor = Rotor3::from_euler_angles(alpha, beta, gamma);
        let mat = rotor.into_matrix();
        let rotor2 = mat.into_rotor3();
        let mat2 = rotor2.into_matrix();
        println!("test {}", i);
        println!("{:?}", mat);
        println!("{:?}", mat2);
        println!("{:?}", rotor);
        println!("{:?}", rotor2);
        println!("========================");
    }



}
```

### CODE REVIEW

**Comment by termhn** [comment]
Thank you for doing this!!

Mat3x4 and Mat3x8 are simply Mat3s but with each component as an f32x4 or f32x8 respectively. You should be able to copy this implementation directly into the existing macro and have it Just Work TM for all the Mat3 types.

Also if you could copy that test program into one or more actual test blocks at the bottom of mat.rs that would be awesome, see this for a template: https://github.com/termhn/ultraviolet/blob/master/src/rotor.rs#L788-L844

**Comment by thenlevy** [comment]
Regarding the implementation for Mat3x4 and Mat3x8, I'm facing the problem that the f32 `copysign` method is called `flip_signs` for f32x4 and f32x8. Maybe two impl blocks are needed ?

**Comment by termhn** [comment]
Ah, unfortunate ... I'll talk to lokathor about perhaps unifying that
naming but for now there should already be separate macros for the wide vs
non-wide types (called impl_mat3s! and impl_mat3s_wide! or something to
that effect) which you should be able to use for this

**Comment by thenlevy** [comment]
I've added tests and implementation for Mat3x4 and Mat3x8. There were only one impl blocks called `mat3s` that implemented the 3 types, so I created two impl blocks called impl_mat3 and impl_mat3_wide

**Comment by termhn** [comment]
Awesome looks great! Thanks so much for doing this :D

**Pull request merged**
