### PR TITLE
Implement serde traits for rotors and bivector

### PR DESCRIPTION
**Pull request by thenlevy**
Here is a proposition to implement Issue #74 
Since, rotors and bivectors do not implement `PartialEq`, I addapted the methods from serde_test to write the unit tests for deserialization

### CODE REVIEW

**Comment by termhn** [comment]
Honestly (non-wide) Bivecs and Rotors should just implement PartialEq, but if you don't want to do that as part of this PR that's definitely understandable

**Comment by thenlevy** [comment]
No problem, I will add it tomorrow.

 I thought that Bivec and Rotor did not implement PartialEq for some mathematical reasons, since I believe that two Bivec with different components can represent the same plane for example.

**Comment by thenlevy** [comment]
Hey, this is just a ping to say that this PR is ready for review/comments

**Review by termhn — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
