### PR TITLE
Add bytemuck optional feature

### PR DESCRIPTION
**Pull request by JMS55**

### CODE REVIEW

**Comment by termhn** [comment]
Thanks! A couple of things:

1. Please feature gate the impls for Isometry, Similarity by the "transform" feature
2. Could you add impls for f64 versions under "f64" feature?
3. Could you add impls for integer versions under "int" feature?

If you'd rather not do 2 and 3 I'd be happy to merge this after 1!

**Comment by JMS55** [comment]
Sure. However, in regards to 1, I don't see the feature anywhere in Cargo.toml?

**Comment by termhn** [comment]
Ah you're right, I confused myself... at one point I had made a transform feature but removed it again. So yeah, remove those cfg's 😅  One more thing, could you add a line in CHANGELOG.md under the unreleased section about it? :) Thanks!!

**Comment by JMS55** [comment]
Done!

**Pull request merged**
